tracer:
  property: "I AM THE DEV"

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/eagle_eye_dev"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update